//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptonit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContact
    {
        public int Id { get; set; }
        public string ContactAddress { get; set; }
        public int CurrencyId { get; set; }
        public string ContactName { get; set; }
        public int UserId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Users Users { get; set; }
    }
}
